### ISSUE TITLE
数据存储问题

### ISSUE THREAD

**Issue by zhangpfly** [KU4NG/OPMS_v3#6]
能不能给出修改数据存储的方法？
现在数据都存在了sqllite3里面，能不能修改数据源为mysql，如何修改？

**Comment by KU4NG** [comment]
![QQ截图20190620151128](https://user-images.githubusercontent.com/32036696/59828561-e25d6280-936d-11e9-823f-ad66b2f3a44b.png)
注释掉这个配置，新增如下配置：
`# MySQL connection
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ezops',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '123456',
    }
}`

**Comment by KU4NG** [comment]
![QQ截图20190620151438](https://user-images.githubusercontent.com/32036696/59828690-23557700-936e-11e9-908b-4e4a459b7202.png)
